language: php

php:
  - 5.6
  - 5.5
  - 5.4

env:
  - REPORT_EXIT_STATUS=1

before_script:
  - cd opengl
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=opengl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - php run-tests.php -n -d extension_dir=$MODULES -d extension=opengl.so -q -x --show-diff

