language: php

php:
  - 5.6
  - 5.5

env:
  - REPORT_EXIT_STATUS=1

before_script:
  - cd opengl
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=opengl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - TEST_PHP_EXECUTABLE=$(which php) make test

