language: php

php:
  - 7.0

env:
  - REPORT_EXIT_STATUS=1

before_install:
  - sudo apt-get install freeglut3-dev;

before_script:
  - phpize
  - ./configure --quiet
  - make all install
  - echo "extension=opengl.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - TEST_PHP_EXECUTABLE=$(which php) make test

